### ISSUE TITLE
Ally

### ISSUE THREAD

**Issue by nelsonic** [iteles/learning#4]
This might interest you: https://github.com/addyosmani/a11y :wink:

**Comment by iteles** [comment]
:heart_eyes: Will try it out, see if it runs on localhost too :+1:

**Comment by iteles** [comment]
No longer maintained:

![image](https://user-images.githubusercontent.com/4185328/79368955-226a8300-7f48-11ea-9ea1-c03c544871ec.png)
![image](https://user-images.githubusercontent.com/4185328/79369000-31e9cc00-7f48-11ea-810e-380e989ffaab.png)
